version: "3"

name: ipfs-filter-prj

services:
  apisix:
    image: apache/apisix:latest
    # image: apache/apisix:${APISIX_IMAGE_TAG:-3.3.0-debian}    ## Used in file-proxy
    restart: always
    user: root        # No used in file-proxy. The 'user: 1000:1000' doesn't work in Ubuntu 22.04/Manjaro 22.1.3, only works 'user: root'.
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./custom-plugins:/opt/apisix/plugins:ro
      - ./openapi.yaml:/usr/local/apisix/conf/openapi.yaml:ro     ## Used in file-proxy example
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "12379:2379/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
