apisix:
  extra_lua_path: "/opt/?.lua"
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

nginx_config:
  http:
    custom_lua_shared_dict:
      my_shared_dict: 10m    # Specify the size in MB of the shared memory zone (change as needed)

deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds

plugins:
  - serverless-pre-function       # Used in 1st ini example
  - pipeline-request              # Used in 1st ini example
  - proxy-rewrite                 # Used in Pass-through VT API example
  - serverless-post-function      # Used in Pass-through VT API example
  - file-proxy                    # Used in file-proxy example
  - server-info
  - mocking                       # Used to create mocks
  - step1-check-local-cache
  - step2-conditional-call
  - ipfs-cache-workflow
  - api1-plugin
  - api2-plugin

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
  server-info:                   # Custom config for server-info plugin
    report_ttl: 60